services:
  db:
    image: postgres:16
    container_name: doughlab_container
    restart: always
    environment:
      - POSTGRES_USER=doughlab
      - POSTGRES_PASSWORD=doughlab
      - POSTGRES_DB=doughlab
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
